import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* UX4G CSS */}
        <link rel="stylesheet" href="/ux4g/css/ux4g-min.css" />
        <link rel="stylesheet" href="/ux4g/css/theme.css" />
        <link rel="stylesheet" href="/ux4g/css/card.css" />
        <link rel="stylesheet" href="/ux4g/css/ux4g-date-time.css" />
      </head>

      <body>
        {children}
      </body>
    </html>
  );
}
